export interface ProdDetLang {
    prodDetsEn:string,
    nameEn:string,
    descriptionEn:string,
    quantEn:String,
    priceEn:string,
    catEn:string,
    sizeDimEn:string,
    backEn:String,
    prodDetsAr:string,
    nameAr:string,
    descriptionAr:string,
    quantAr:String,
    priceAr:string,
    catAr:string,
    sizeDimAr:string,
    backAr:String,
}
