export interface ProdLang {
    searchEn:string,
    nameEn:string,
    quantEn:string,
    priceEn:string,
    imgEn:string,
    detsEn:string,
    editEn:string,
    deleteEn:String,
    searchAr:string,
    nameAr:string,
    quantAr:string,
    priceAr:string,
    imgAr:string,
    detsAr:string,
    editAr:string,
    deleteAr:String,
}
